apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    # 'proxy' means Grafana's backend connects to Prometheus
    # (instead of your browser trying to connect directly)
    access: proxy
    # We use the Docker Service Name 'prometheus' defined in docker-compose
    url: http://prometheus:9090
    isDefault: true